# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PuyoSimulator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuyoSimulator
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/DynamicLinks'

# pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  target 'PuyoSimulatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PuyoSimulator-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuyoSimulator-tvOS

  target 'PuyoSimulator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

