# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PuyoSimulator' do

  # from: https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuyoSimulator
  pod 'GoogleAppMeasurement', '~> 5.4.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/AdMob', '~> 5.15.0'

# pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  target 'PuyoSimulatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PuyoSimulator-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PuyoSimulator-tvOS

  target 'PuyoSimulator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# https://github.com/facebook/react-native/issues/12814
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
